# Generated by Django 6.0 on 2025-12-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disciplina', '0001_initial'),
        ('Pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estatura_cm', models.SmallIntegerField(blank=True, null=True)),
                ('peso_kg', models.SmallIntegerField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Disciplina.disciplina')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pais.pais')),
            ],
        ),
    ]
